plugins {
    id "com.android.application" version "8.5.2" apply false
    id "org.jetbrains.kotlin.android" version "2.0.21" apply false
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"
}